[package]
name = "train-against-self"
version = "0.1.0"
edition = "2024"

[dependencies]
qchess-bot = { path = "../qchess-bot" }
burn = { version = "0.17.1", features = ["train"] }
shakmaty = "0.27.3"
rand = "0.9.1"

[features]
default = ["wgpu"]
cpu = ["burn/ndarray"]
wgpu = ["burn/wgpu"]
cuda = ["burn/cuda"]
