[package]
name = "train-against-self"
version = "0.1.0"
edition = "2024"

[dependencies]
qchess-bot = { path = "../qchess-bot" }
burn = { version = "0.21.0", features = ["train"] }
shakmaty = "0.30.1"
rand = "0.10.2"

[features]
default = ["wgpu"]
cpu = ["burn/ndarray"]
wgpu = ["burn/wgpu"]
cuda = ["burn/cuda"]
tch = ["burn/tch"]
